### ISSUE TITLE
Repo added incorrect on Rocky Linux & possibility to handle repos outside module

### ISSUE THREAD

**Issue by olaskjeldal** [indiana-university/puppet-duo_unix#24]
I'm trying to use this module on Rocky Linux (RIP CentOS...), it adds the repo as
"https://pkg.duosecurity.com/Rocky/$releasever/$basearch" in the "/etc/yum.repos.d/duosecurity.repo" file.

However, there's no such repo (or symlink) available on duosecurity's repo.. Not sure if this would be the prefered way?

Aditionally; is there any way to make the module not handle the repos so we can handle this ourselves? 
I prefer to use internal repositories.. (servers usually don't have direct internet access).

**Comment by avitacco** [comment]
Sorry for the delay in responding to this issue, was on PTO for a week. This module doesn't officially support Rocky but I will look into making it work for you. I will also look at adding a parameter to control repo management.

**Comment by avitacco** [comment]
Closing issue as #25 has added the requested functionality.

This results in Rocky and Alma using the RedHat version.
