### ISSUE TITLE
Using ensure => latest throws an error

### ISSUE THREAD

**Issue by rodehoed** [indiana-university/puppet-duo_unix#32]
First of all, thanks for this replacement!

We noticed that when we set _ensure_ to _latest_ (default = present) , the puppet agent will give an error:
`
Error: Failed to apply catalog: Validation of File[/etc/duo/login_duo.conf] failed: You cannot specify more than one of content, source, target (file: /etc/puppetlabs/code/modules/duo_unix/manifests/init.pp, line: 140)`

This error is not cause by de Package resource but with the File resource (etc/duo/login_duo.conf) where the same $ensure is used. To my knowledge this cannot work this way. 

For now I changed the Package resource to latest by hand.

**Comment by avitacco** [comment]
Thank you for bringing this to my attention. I have an idea for a fix for this and will work to have a new version released soon.

**Comment by avitacco** [comment]
I hope I've fixed the issue you were facing. There are now separate `*_ensure` parameters instead of just one shared one. Thank you @rodehoed for your help in ensuring this module is functional and useful for the community.

**Comment by rodehoed** [comment]
Hi @avitacco . Wow, you can fix it faster then I can answer :+1:  It works as advertised now! Thx
