### ISSUE TITLE
Using CERN-CERT pam_2fa with iu-duo_unix

### ISSUE THREAD

**Issue by cmd-ntrf** [indiana-university/puppet-duo_unix#35]
We would like to use iu-duo_unix while also using the approach proposed by CERN to protect the second factor:
https://cern-cert.github.io/pam_2fa/

iu-duo_unix is essentially missing three things:
- pam_ssh_user_auth package
- Inserting `auth pam_ssh_user_auth.so`, `auth pam_deny` and `auth /lib64/security/pam_duo.so` in /etc/pam.d/sshd
- Inserting `AuthenticationMethods gssapi-with-mic,keyboard-interactive:pam publickey,keyboard-interactive:pam keyboard-interactive:pam,keyboard-interactive:pam` in /etc/ssh/sshd_config.

Would you be interested in a PR that implements this in iu-duo_unix?

**Comment by mboisson** [comment]
This should be closed by https://github.com/indiana-university/puppet-duo_unix/pull/38
